version: '3'
services:
  app:
    build: ./
    restart: always
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
    networks:
      network:
        ipv4_address: 172.20.0.12

networks:
  network:
    external:
      name: nginx-proxy-manager_default
