# Deploy app

name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }} 
        command_timeout: 30m
        script: |
          cd ~/repos/react-portfolio
          git pull origin main
          git status
          npm install --only=prod
          if [ $(docker ps -q -f name=react-portfolio) ]; then
            docker-compose down
          fi
          docker-compose build
          docker-compose up -d
