# This workflow will do a clean install of node dependencies
name: Install and build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: 20.x
    - run: npm i
    - run: npm run build --if-present
